# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install flask-sqlalchemy

before_script:
    - uname -a
    - printenv
    - pip list

script:
    - date
    - ls -al
    - make idb-tests
    - ls -al
    - make IDB.html
    - ls -al
    - make IDB.log
    - ls -al
    - make test
    - ls -al
#	- make check
