FORMAT: 1A
HOST: http://darkritual.cards/api/

# Data: The Gathering API

Data: The Gathering is a simple API allowing players to view cards, sets, and artists.

## All Editions of a Page of Cards [/cards/{page}]

### List 25 cards [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Dark Ritual",
                "card_id": "dark-ritual",
                "url": "https://api.deckbrew.com/mtg/cards/dark-ritual",
                "types": [
                    "instant"
                ],
                "colors": [
                    "black"
                ],
                "cmc": 1,
                "cost": "{B}",
                "text": "Add {B}{B}{B} to your mana pool.",
                "formats": {
                    "commander": "legal",
                    "legacy": "legal",
                    "vintage": "legal"
                },
                "power": "",
                "toughness": ""
            },
            ...
        ]

## All Editions of One Card [/cards/{id}]

### List ONE card by id [GET]

+ Response 200 (application/json)

        {
            "name": "Dark Ritual",
            "id": "dark-ritual",
            "types": [
                "instant"
            ],
            "colors": [
                "black"
            ],
            "cmc": 1,
            "cost": "{B}",
            "text": "Add {B}{B}{B} to your mana pool.",
            "formats": {
                "commander": "legal",
                "legacy": "legal",
                "vintage": "legal"
            },
            "power": "",
            "toughness": ""
            "multiverse_ids": [
                {
                    "multiverse_id": 1149,
                    "artist_id": "sandra-everingham",
                    "set_id": "3ED",
                    "card_id": "dark-ritual",
                    "image_url": "https://image.deckbrew.com/mtg/multiverseid/1149.jpg"
                    "rarity": "common",
                    "flavor": "",
                    "number": "",
                    "layout": "normal"
                },
                ...
            ]
        }
        
## Specific Edition of One Card [/editions/{multiverseid}]

### List ONE card edition by multiverse_id [GET]

+ Response 200 (application/json)

        {
            "multiverse_id": 1149,
            "artist_id": "sandra-everingham",
            "set_id": "3ED",
            "card_id": "dark-ritual",
            "image_url": "https://image.deckbrew.com/mtg/multiverseid/1149.jpg"
            "rarity": "common",
            "flavor": "",
            "number": "",
            "layout": "normal"
        }
            

## Page of Sets [/sets/{page}]

### List 25 sets [GET]

+ Response 200 (application/json)

        [
            {
                "set": "Revised Edition",
                "set_id": "3ED"
            },
            ...
        ]

## All Card Editions in One Set [/sets/{set_id}]

### List card editions by set_id [GET]

+ Response 200 (application/json)

        {
            "set_id": "3ED"
            "name": "Revised Edition"
            "multiverse_ids": [
                {
                    "multiverse_id": 1149,
                    "artist_id": "sandra-everingham",
                    "set_id": "3ED",
                    "card_id": "dark-ritual",
                    "image_url": "https://image.deckbrew.com/mtg/multiverseid/1149.jpg"
                    "rarity": "common",
                    "flavor": "",
                    "number": "",
                    "layout": "normal"
                },
                ...
            ]
        }

## Page of Artists [/artists/{page}]

### List 25 artists [GET]

+ Response 200 (application/json)

        [
            {
                
                "artist_id": "sandra-everingham",
                "artist": "Sandra Everingham"
            },
            ...
        ]

## All Card Editions by One artist [/artists/{artist_id}]

### List card editions by artist_id [GET]

+ Response 200 (application/json)

        {
            "artist_id": "sandra-everingham",
            "artist": "Sandra Everingham",
            "multiverse_ids": [
                {
                    "multiverse_id": 1149,
                    "artist_id": "sandra-everingham",
                    "set_id": "3ED",
                    "card_id": "dark-ritual",
                    "image_url": "https://image.deckbrew.com/mtg/multiverseid/1149.jpg"
                    "rarity": "common",
                    "flavor": "",
                    "number": "",
                    "layout": "normal"
                },
                ...
            ]
        }
